### ISSUE TITLE
I got this error

### ISSUE THREAD

**Issue by Platorius** [miccunifi/TAPE#8]
I got the error below in the picture. I dont know what is wrong. It does not extract frames, but i dont know why. I dont know what these errors means. Do you have any idea ?

![TAPE-error](https://github.com/miccunifi/TAPE/assets/66878092/b99fa88f-e21b-4fdd-803e-54d65f5af918)

**Comment by LorenzoAgnolucci** [comment]
Hi @Platorius!

There is some kind of mistake related to the input video, as the code extracts 0 frames from it. Try checking that everything is correct with the input video, and maybe try with a different one. It is hard to say what the problem is without knowing anything about your video, but I am quite confident that it is a silly mistake that you should be able to fix quite easily.
